export const AUTH_LOGIN ="AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS ="AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILD ="AUTH_LOGIN_FAILD";

export const AUTH_SIGNUP ="AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS ="AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILD ="AUTH_SIGNUP_FAILD";


export const ON_BUTTON_SUBMIT ="ON_BUTTON_SUBMIT";
export const OFF_BUTTON_SUBMIT ="OFF_BUTTON_SUBMIT";

export const CHECK_AUTH_SUCCESS ="CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAILD ="CHECK_AUTH_FAILD";