export const FETCH_TASK ='FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILED = 'FETCH_TASK_FAILED';


export const FILTER_TASK = 'FILTER_TASK';
export const FILTER_TASK_SUCCESS='FILTER_TASK_SUCCESS';

export const ADD_TASK='ADD_TASK';
export const ADD_TASK_SUCCESS='ADD_TASK_SUCCESS';
export const ADD_TASK_FAILD='ADD_TASK_FAILD';


export const SET_TASK_EDITING='SET_TASK_EDITING';

export const SET_TASK_UPDATE='SET_TASK_UPDATE';
export const SET_TASK_UPDATE_SUCCESS='SET_TASK_UPDATE_SUCCESS';
export const SET_TASK_UPDATE_FAILD='SET_TASK_UPDATE_FAILD';

export const SET_TASK_DELETE='SET_TASK_DELETE';
export const SET_TASK_DELETE_SUCCESS='SET_TASK_DELETE_SUCCESS';
export const SET_TASK_DELETE_FAILD='SET_TASK_DELETE_FAILD';

export const REFESH_TASK ='REFESH_TASK';
export const REFESH_TASK_SUCCESS = 'REFESH_TASK_SUCCESS';
export const REFESH_TASK_FAILED = 'REFESH_TASK_FAILED';